language: r
pandoc: false
sudo: true
cache:
- packages
- "/tmp/texlive"
- "/$HOME/texlive"
warnings_are_errors: false
before_install:
- source ./travis/texlive.sh
- tlmgr update --self
- tlmgr install acronym bigfoot blindtext chngcntr cmap nowidow mdframed navigator 
  ocgx2 media9 makecell
  needspace tablefootnote tocloft xpatch multirow bbding mathastext isomath relsize
  niceframe-type1
- if [ $TRAVIS_REPO_SLUG == "HughParsonage/grattex" ]; then tlmgr install tex-gyre
  eulervm bold-extra fancyvrb realboxes manfnt lstaddons; fi
- if [ $TRAVIS_REPO_SLUG == "HughParsonage/grattex" ]; then sudo apt-get install poppler-utils;
  fi
- tlmgr update --all
- sudo apt-get update
- sudo apt-get install texlive-bibtex-extra
#
# Shiny testing:
- "export PHANTOMJS_VERSION=2.1.1"
- "phantomjs --version"
- "export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
- "hash -r"
- "phantomjs --version"
- "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
- "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
- "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
- "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then hash -r; fi"
- "phantomjs --version"
install: echo Installation step
before_script:
- wget http://mirrors.ctan.org/biblio/biber/binaries/Linux/biber-linux_x86_64.tar.gz
- tar xzf biber-linux_x86_64.tar.gz
- export PATH=$PATH:$PWD
- tlmgr update biber chngcntr
- sudo apt-get install -y r-cran-devtools r-cran-rcpp r-cran-bh r-cran-stringi r-cran-hunspell r-cran-survey r-cran-dplyr r-cran-tidyr r-cran-readr r-cran-ggplot2 r-cran-ggrepel r-cran-haven r-cran-survival
- Rscript travis-make.R
- Rscript -e 'RQ("shinytest", install_github("rstudio/shinytest", quiet = TRUE, quick = TRUE))'

script: 
- cd shiny/NegativeGearing-vs-Occupation
- R -f run_tests.R
- cd ../..
- Rscript -e 'knitr::knit("CGT_and_neg_gearing_parent.Rnw", quiet = TRUE)'
- pdflatex -interaction=nonstopmode CGT_and_neg_gearing_parent.tex > /dev/null
- pdflatex -interaction=nonstopmode CGT_and_neg_gearing_parent.tex
- biber CGT_and_neg_gearing_parent
- pdflatex -interaction=batchmode CGT_and_neg_gearing_parent.tex > /dev/null
- pdflatex -interaction=batchmode CGT_and_neg_gearing_parent.tex > /dev/null
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: YH+WdKpr0qTZ4O1QRm8EVihB7YCZIvmTxeCg8h+q8Q9Z2UXa1dPuuLqM/FFdNSDjZ7gYZ8Pi6gX04rEIvmbbJ++YwRGAJ7X1nOtfq8/DZgTwEA4i5hexDuw+i9FtGCS8AptLkO35ZEo+4SU3kOTRRXjJIZt29iGEps18F9+z9UAX3ntLQpmISPWgvjJUO80DY2pSg3iF7msaa6Llex9HWV6JI7CtsIkkgrJLnzprzv5Pi7k+Yq59uCH/c1gTu4wmVtKFpAxDR/58styuIAnInFb427gs2hvwik7c2Ury1LzL71lnc27NCy/rf25sL3zoHVrSj/gxt/LMVP2yUr3DPYyeEAONANTZeqh5l6l49+jeAkEE0hkU9RV6fFX06V41av3tG63blBfwLFcoPUHF9nxqp2M5gpoV6qzGcNxOpjmQ1kkB5F5TrnQk0QYeW/4USWI2d9etkZaWAadgyEBUSSANFXPlOaM0y1PgXeA0jhKMdj7dM/5rkQkE28S50qLeoDo0+4BWp2AgVxNwcgVdBXamJ2d2j9iweNi1RotiU4zA6RizqdKtsp2qH1TXoDrOrrj0w94vP2fbQ457Sp/m7v7AswWwFfxoI0i3wEyQL30j+CSq/c4EOS6QvwXhMA6Dqc2C6Lk1p8ddoaGj2ItX5nkPB2oAgh2dyFiZIP5qevU=
  file: CGT_and_neg_gearing_parent.pdf
  on:
    repo: grattan/NegativeGearing2016
    branch: master
