language: r
pandoc: false
sudo: true
cache:
- packages
- "/tmp/texlive"
- "/$HOME/texlive"
warnings_are_errors: false
r_github_packages:
- HughParsonage/TeXCheckR
- HughParsonage/grattanReporter
before_install:
- source ./travis/texlive.sh
- tlmgr update --self
- tlmgr install acronym bigfoot blindtext chngcntr cmap nowidow mdframed navigator
  needspace tablefootnote tocloft xpatch multirow bbding mathastext isomath relsize
  niceframe-type1
- if [ $TRAVIS_REPO_SLUG == "HughParsonage/grattex" ]; then tlmgr install tex-gyre
  eulervm bold-extra fancyvrb realboxes manfnt lstaddons; fi
- if [ $TRAVIS_REPO_SLUG == "HughParsonage/grattex" ]; then sudo apt-get install poppler-utils;
  fi
- tlmgr update --all
- sudo apt-get update
- sudo apt-get install texlive-bibtex-extra
install: echo Installation step
before_script:
- wget http://mirrors.ctan.org/biblio/biber/binaries/Linux/biber-linux_x86_64.tar.gz
- tar xzf biber-linux_x86_64.tar.gz
- export PATH=$PATH:$PWD
- tlmgr update biber chngcntr
- Rscript do_make.R
- pdflatex -interaction=nonstopmode CGT_and_neg_gearing_parent.Rnw > /dev/null
- biber CGT_and_neg_gearing_parent
- pdflatex -interaction=batchmode CGT_and_neg_gearing_parent.Rnw > /dev/null
- pdflatex -interaction=batchmode CGT_and_neg_gearing_parent.Rnw > /dev/null
deploy:
  provider: releases
  api_key:
    secure: YH+WdKpr0qTZ4O1QRm8EVihB7YCZIvmTxeCg8h+q8Q9Z2UXa1dPuuLqM/FFdNSDjZ7gYZ8Pi6gX04rEIvmbbJ++YwRGAJ7X1nOtfq8/DZgTwEA4i5hexDuw+i9FtGCS8AptLkO35ZEo+4SU3kOTRRXjJIZt29iGEps18F9+z9UAX3ntLQpmISPWgvjJUO80DY2pSg3iF7msaa6Llex9HWV6JI7CtsIkkgrJLnzprzv5Pi7k+Yq59uCH/c1gTu4wmVtKFpAxDR/58styuIAnInFb427gs2hvwik7c2Ury1LzL71lnc27NCy/rf25sL3zoHVrSj/gxt/LMVP2yUr3DPYyeEAONANTZeqh5l6l49+jeAkEE0hkU9RV6fFX06V41av3tG63blBfwLFcoPUHF9nxqp2M5gpoV6qzGcNxOpjmQ1kkB5F5TrnQk0QYeW/4USWI2d9etkZaWAadgyEBUSSANFXPlOaM0y1PgXeA0jhKMdj7dM/5rkQkE28S50qLeoDo0+4BWp2AgVxNwcgVdBXamJ2d2j9iweNi1RotiU4zA6RizqdKtsp2qH1TXoDrOrrj0w94vP2fbQ457Sp/m7v7AswWwFfxoI0i3wEyQL30j+CSq/c4EOS6QvwXhMA6Dqc2C6Lk1p8ddoaGj2ItX5nkPB2oAgh2dyFiZIP5qevU=
  file: CGT_and_neg_gearing_parent.pdf
  on:
    repo: grattan/NegativeGearing2016
